//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E02_ConsoleClientDayOfWeek.GetDayBulService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDayBulService.IGetDayService")]
    public interface IGetDayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDayService/GetDateBul", ReplyAction="http://tempuri.org/IGetDayService/GetDateBulResponse")]
        string GetDateBul(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDayService/GetDateBul", ReplyAction="http://tempuri.org/IGetDayService/GetDateBulResponse")]
        System.Threading.Tasks.Task<string> GetDateBulAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDayServiceChannel : E02_ConsoleClientDayOfWeek.GetDayBulService.IGetDayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDayServiceClient : System.ServiceModel.ClientBase<E02_ConsoleClientDayOfWeek.GetDayBulService.IGetDayService>, E02_ConsoleClientDayOfWeek.GetDayBulService.IGetDayService {
        
        public GetDayServiceClient() {
        }
        
        public GetDayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDateBul(System.DateTime date) {
            return base.Channel.GetDateBul(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDateBulAsync(System.DateTime date) {
            return base.Channel.GetDateBulAsync(date);
        }
    }
}
