//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E05_ConsoleClientIIS.StringOccurrencesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringOccurrencesService.IStringsService")]
    public interface IStringsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsService/GetNumberOfTimesSecondStringContainsFirstStrin" +
            "g", ReplyAction="http://tempuri.org/IStringsService/GetNumberOfTimesSecondStringContainsFirstStrin" +
            "gResponse")]
        int GetNumberOfTimesSecondStringContainsFirstString(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsService/GetNumberOfTimesSecondStringContainsFirstStrin" +
            "g", ReplyAction="http://tempuri.org/IStringsService/GetNumberOfTimesSecondStringContainsFirstStrin" +
            "gResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfTimesSecondStringContainsFirstStringAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringsServiceChannel : E05_ConsoleClientIIS.StringOccurrencesService.IStringsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringsServiceClient : System.ServiceModel.ClientBase<E05_ConsoleClientIIS.StringOccurrencesService.IStringsService>, E05_ConsoleClientIIS.StringOccurrencesService.IStringsService {
        
        public StringsServiceClient() {
        }
        
        public StringsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumberOfTimesSecondStringContainsFirstString(string first, string second) {
            return base.Channel.GetNumberOfTimesSecondStringContainsFirstString(first, second);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfTimesSecondStringContainsFirstStringAsync(string first, string second) {
            return base.Channel.GetNumberOfTimesSecondStringContainsFirstStringAsync(first, second);
        }
    }
}
